apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhook-app
  template:
    metadata:
      labels:
        app: webhook-app
    spec:
      containers:
      - name: webhook-server
        image: kingulec/webhook-server:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls-certs
          mountPath: /certs
          readOnly: true
      # SET env variables for certificates paths
        env:
        - name: TLS_CERT_PATH
          value: "/certs/tls.crt"
        - name: TLS_KEY_PATH
          value: "/certs/tls.key"
      # Secret volume for TLS certificates
      volumes:
      - name: tls-certs
        secret:
          secretName: webhook-server-tls