apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-ingress
 # annotations:
 #   traefik.ingress.kubernetes.io/service.serverstransport: webhook-insecure
spec:
  tls:
  - hosts:
    - webhook.example.com
    secretName: webhook-server-tls
  rules:
  - host: webhook.example.com
    http:
      paths:
      - path: /webhook
        pathType: Exact
        backend:
          service:
            name: webhook-service
            port:
              number: 443
