apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  selector:
    app: webhook-app
  ports:
    - protocol: TCP
      port: 443 # port in claster
      targetPort: 8443 # port in pod
  type: ClusterIP