apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-webhook-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-webhook
  template:
    metadata:
      labels:
        app: my-webhook
    spec:
      containers:
      - name:  webhook-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - name: tls-certs
          mountPath: /certs
          readOnly: true
      # SET env variables for certificates paths
        env:
        - name: TLS_CERT_PATH
          value: "/certs/tls.crt"
        - name: TLS_KEY_PATH
          value: "/certs/tls.key"
      # Secret volume for TLS certificates
      volumes:
      - name: tls-certs
        secret:
          secretName: my-webhook-tls